/*
 * Source: PkgCutServicesTrxFormData.java - Generated by OBCOM SQL Wizard 5.1.295
 * Author: Felipe Gonzalez Mendoza (Tesoreria General de la Republica)
 *
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
 *
 * All rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
 * used  under  the  terms of its associated license document. You may NOT copy,
 * modify, sublicense, or distribute this source file or portions of  it  unless
 * previously  authorized in writing by OBCOM INGENIERIA S.A. In any event, this
 * notice and above copyright must always be included verbatim with this file.
 */

package cl.teso.reca.pkgcutservicestrx.classes.Messages;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Calendar;

/**
 * Implements the "PKG_CUT_SERVICES$TRX_FORM_DATA" user-defined object.
 */
public class TrxFormData implements Serializable
{
    private static final long serialVersionUID = 1L;

    // Fields of the user-defined object
    private String      usuario;         // VARCHAR2(4000)
    private BigDecimal  rutIra;          // NUMBER
    private String      rutIraDv;        // CHAR(1)
    private BigDecimal  rutContrib;      // NUMBER
    private String      dvContrib;       // CHAR(1)
    private String      signoForm;       // CHAR(1)
    private BigDecimal  formTipo;        // NUMBER
    private String      formVer;         // CHAR(1)
    private BigDecimal  formFolio;           // NUMBER
    private Calendar    periodo;         // DATE
    private String      items;           // VARCHAR2(4000)
    private String      idOrigen;        // VARCHAR2(4000)
    //private String      paquete;         // VARCHAR2(4000)
    //private String      ruta;            // VARCHAR2(4000)
    private BigDecimal  folioF01;        // NUMBER
    private Calendar    fechaOrigen;     // DATE
    private Calendar    fechaCaja;       // DATE
    //private BigDecimal  loteId;          // NUMBER
    private BigDecimal  loteCanal;       // NUMBER
    private BigDecimal  loteTipo;        // NUMBER
   // private BigDecimal  cutMovEstado;    // NUMBER
   // private String      esReversa;       // CHAR(1)
   // private BigDecimal  movIdAnular;     // NUMBER
   // private String      frmOpcion;       // CHAR(1)
   // private String      fmtDataErr;      // VARCHAR2(4000)
   // private String      fmtDataSal;      // VARCHAR2(4000)
   // private String      motivo;          // VARCHAR2(4000)
   // private String      resolucion;      // VARCHAR2(4000)

    /**
     * Constructor.
     */
    public TrxFormData()
    {
    }

    /**
     * Gets the USUARIO value of this PkgCutServicesTrxFormData.
     */
    public String getUsuario()
    {
        return usuario;
    }

    /**
     * Sets the USUARIO value of this PkgCutServicesTrxFormData.
     */
    public void setUsuario(String usuario)
    {
        this.usuario = usuario;
    }

    /**
     * Gets the RUT_IRA value of this PkgCutServicesTrxFormData.
     */
    public BigDecimal getRutIra()
    {
        return rutIra;
    }

    /**
     * Sets the RUT_IRA value of this PkgCutServicesTrxFormData.
     */
    public void setRutIra(BigDecimal rutIra)
    {
        this.rutIra = rutIra;
    }

    /**
     * Gets the RUT_IRA_DV value of this PkgCutServicesTrxFormData.
     */
    public String getRutIraDv()
    {
        return rutIraDv;
    }

    /**
     * Sets the RUT_IRA_DV value of this PkgCutServicesTrxFormData.
     */
    public void setRutIraDv(String rutIraDv)
    {
        this.rutIraDv = rutIraDv;
    }

    /**
     * Gets the RUT_CONTRIB value of this PkgCutServicesTrxFormData.
     */
    public BigDecimal getRutContrib()
    {
        return rutContrib;
    }

    /**
     * Sets the RUT_CONTRIB value of this PkgCutServicesTrxFormData.
     */
    public void setRutContrib(BigDecimal rutContrib)
    {
        this.rutContrib = rutContrib;
    }

    /**
     * Gets the DV_CONTRIB value of this PkgCutServicesTrxFormData.
     */
    public String getDvContrib()
    {
        return dvContrib;
    }

    /**
     * Sets the DV_CONTRIB value of this PkgCutServicesTrxFormData.
     */
    public void setDvContrib(String dvContrib)
    {
        this.dvContrib = dvContrib;
    }

    /**
     * Gets the SIGNO_FORM value of this PkgCutServicesTrxFormData.
     */
    public String getSignoForm()
    {
        return signoForm;
    }

    /**
     * Sets the SIGNO_FORM value of this PkgCutServicesTrxFormData.
     */
    public void setSignoForm(String signoForm)
    {
        this.signoForm = signoForm;
    }

    /**
     * Gets the FORM_TIPO value of this PkgCutServicesTrxFormData.
     */
    public BigDecimal getFormTipo()
    {
        return formTipo;
    }

    /**
     * Sets the FORM_TIPO value of this PkgCutServicesTrxFormData.
     */
    public void setFormTipo(BigDecimal formTipo)
    {
        this.formTipo = formTipo;
    }

    /**
     * Gets the FORM_VER value of this PkgCutServicesTrxFormData.
     */
    public String getFormVer()
    {
        return formVer;
    }

    /**
     * Sets the FORM_VER value of this PkgCutServicesTrxFormData.
     */
    public void setFormVer(String formVer)
    {
        this.formVer = formVer;
    }

    /**
     * Gets the FOLIO value of this PkgCutServicesTrxFormData.
     */
    public BigDecimal getFormFolio()
    {
        return formFolio;
    }

    /**
     * Sets the FOLIO value of this PkgCutServicesTrxFormData.
     */
    public void setFormFolio(BigDecimal formFolio)
    {
        this.formFolio = formFolio;
    }

    /**
     * Gets the PERIODO value of this PkgCutServicesTrxFormData.
     */
    public Calendar getPeriodo()
    {
        return periodo;
    }

    /**
     * Sets the PERIODO value of this PkgCutServicesTrxFormData.
     */
    public void setPeriodo(Calendar periodo)
    {
        this.periodo = periodo;
    }

    /**
     * Gets the ITEMS value of this PkgCutServicesTrxFormData.
     */
    public String getItems()
    {
        return items;
    }

    /**
     * Sets the ITEMS value of this PkgCutServicesTrxFormData.
     */
    public void setItems(RecaItems[] recaItems) throws Exception
    {
        items = RecaItems.PackTouplesReca(recaItems);
    }


    /**
     * Gets the ID_ORIGEN value of this PkgCutServicesTrxFormData.
     */
    public String getIdOrigen()
    {
        return idOrigen;
    }

    /**
     * Sets the ID_ORIGEN value of this PkgCutServicesTrxFormData.
     */
    public void setIdOrigen(String idOrigen)
    {
        this.idOrigen = idOrigen;
    }

    /**
     * Gets the PAQUETE value of this PkgCutServicesTrxFormData.
     */
 /*   public String getPaquete()
    {
        return paquete;
    }*/

    /**
     * Sets the PAQUETE value of this PkgCutServicesTrxFormData.
     */
 /*   public void setPaquete(String paquete)
    {
        this.paquete = paquete;
    }*/

    /**
     * Gets the RUTA value of this PkgCutServicesTrxFormData.
     */
  /*  public String getRuta()
    {
        return ruta;
    }
*/
    /**
     * Sets the RUTA value of this PkgCutServicesTrxFormData.
     */
 /*   public void setRuta(String ruta)
    {
        this.ruta = ruta;
    }
*/
    /**
     * Gets the FOLIO_F01 value of this PkgCutServicesTrxFormData.
     */
    public BigDecimal getFolioF01()
    {
        return folioF01;
    }

    /**
     * Sets the FOLIO_F01 value of this PkgCutServicesTrxFormData.
     */
    public void setFolioF01(BigDecimal folioF01)
    {
        this.folioF01 = folioF01;
    }

    /**
     * Gets the FECHA_ORIGEN value of this PkgCutServicesTrxFormData.
     */
    public Calendar getFechaOrigen()
    {
        return fechaOrigen;
    }

    /**
     * Sets the FECHA_ORIGEN value of this PkgCutServicesTrxFormData.
     */
    public void setFechaOrigen(Calendar fechaOrigen)
    {
        this.fechaOrigen = fechaOrigen;
    }

    /**
     * Gets the FECHA_CAJA value of this PkgCutServicesTrxFormData.
     */
    public Calendar getFechaCaja()
    {
        return fechaCaja;
    }

    /**
     * Sets the FECHA_CAJA value of this PkgCutServicesTrxFormData.
     */
    public void setFechaCaja(Calendar fechaCaja)
    {
        this.fechaCaja = fechaCaja;
    }

   
    /**
     * Gets the LOTE_CANAL value of this PkgCutServicesTrxFormData.
     */
    public BigDecimal getLoteCanal()
    {
        return loteCanal;
    }

    /**
     * Sets the LOTE_CANAL value of this PkgCutServicesTrxFormData.
     */
    public void setLoteCanal(BigDecimal loteCanal)
    {
        this.loteCanal = loteCanal;
    }

    /**
     * Gets the LOTE_TIPO value of this PkgCutServicesTrxFormData.
     */
    public BigDecimal getLoteTipo()
    {
        return loteTipo;
    }

    /**
     * Sets the LOTE_TIPO value of this PkgCutServicesTrxFormData.
     */
    public void setLoteTipo(BigDecimal loteTipo)
    {
        this.loteTipo = loteTipo;
    }      

}
