/*
 * File: PkgCajaServicesException.java  2009-07-15 17:54:49-04:00
 * User: Felipe Gonzalez (DP S.A.)
 *
 * File generated by OBCOM SQL Wizard 5.1.248 (www.obcom.cl).
 * DO NOT EDIT THIS FILE <<Signature:P2ZpDY2hX3u4-iKtvmr9no>>.
 */

package cl.teso.reca.portalsrv.pkgcajaservices;

/**
 * Exception thrown when the execution of a procedure fails.
 */
public class PkgCajaServicesException extends Exception
{
    private static final long serialVersionUID = 1L;

    /**
     * Create a new PkgCajaServicesException.
     */
    public PkgCajaServicesException()
    {
        super();
    }

    /**
     * Create a new PkgCajaServicesException with supplied message.
     */
    public PkgCajaServicesException(String message)
    {
        super(message);
    }

    /**
     * Create a new PkgCajaServicesException with supplied cause.
     */
    public PkgCajaServicesException(Throwable cause)
    {
        super(cause);
    }

    /**
     * Create a new PkgCajaServicesException with supplied message and cause.
     */
    public PkgCajaServicesException(String message, Throwable cause)
    {
        super(message, cause);
    }
}
