/*
 * Source: AdfLiquidaCaller.java - Generated by OBCOM SQL Wizard 5.1.295
 * Author: Felipe Gonzalez Mendoza (Tesoreria General de la Republica)
 *
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
 *
 * All rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
 * used  under  the  terms of its associated license document. You may NOT copy,
 * modify, sublicense, or distribute this source file or portions of  it  unless
 * previously  authorized in writing by OBCOM INGENIERIA S.A. In any event, this
 * notice and above copyright must always be included verbatim with this file.
 */

package cl.teso.reca.pkgcutservicestrx;

import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import javax.sql.DataSource;
import javax.sql.RowSet;

/**
 * Implements a caller of procedure "PKG_CUT_SERVICES_TRX.ADF_LIQUIDA".
 * <pre>
 * TOUPLESTGF         VARCHAR2(4000)     Input
 * CONTEXTTGFIN       VARCHAR2(4000)     Input
 * CONTEXTTGFOUT      VARCHAR2(4000)     Output
 * MESSAGESTGF        VARCHAR2(4000)     Output
 * RESULTADO          NUMBER             Output
 * </pre>
 */
public class AgregaCondonaVmsCaller extends ProcedureCaller
{
    /**
     * Executes procedure "PKG_CUT_SERVICES_TRX.ADF_LIQUIDA" using a DataSource.
     */
    public static AgregaCondonaVmsResult execute(DataSource dataSource, String touplestgf, String contexttgfin, String sistemaCondonacion)
        throws SQLException
    {
        Connection conn = dataSource.getConnection();
        try {
            return execute(conn, touplestgf, contexttgfin, sistemaCondonacion);
        } finally {
            conn.close();
        }
    }
    

    /**
     * Executes procedure "PKG_CUT_SERVICES_TRX.ADF_LIQUIDA" using a Connection.
     */
    public static AgregaCondonaVmsResult execute(Connection conn, String touplestgf, String contexttgfin, String sistemaCondonacion)
        throws SQLException
    {
        AgregaCondonaVmsResult result = new AgregaCondonaVmsResult();
        ArrayList resultSets = new ArrayList();
        CallableStatement call = conn.prepareCall("{call PKG_CUT_SERVICES_TRX.AGREGA_CONDONA_VMS(?,?,?,?,?,?,?,?,?,?)}");
        try {
            call.setString(1, touplestgf);
            call.setString(2, contexttgfin);                        
            call.setString(3, sistemaCondonacion);
            call.registerOutParameter(4, Types.VARCHAR);
            call.registerOutParameter(5, Types.VARCHAR);
            call.registerOutParameter(6, Types.VARCHAR);            
            call.registerOutParameter(7, Types.NUMERIC);         
            call.registerOutParameter(8, Types.NUMERIC);
            call.registerOutParameter(9, Types.NUMERIC);    
            call.registerOutParameter(10, Types.DATE);  
            
            int updateCount = 0;
            boolean haveRset = call.execute();
            while (haveRset || updateCount != -1) {
                if (!haveRset)
                    updateCount = call.getUpdateCount();
                else
                    resultSets.add(toRowSet(call.getResultSet()));
                haveRset = call.getMoreResults();
            }
            result.setTouplestgfout(call.getString(4));
            result.setContexttgfout(call.getString(5));
            result.setMessagestgf(call.getString(6));
            result.setResultado(call.getBigDecimal(7));
            result.setCondonaciones(call.getBigDecimal(8));
            result.setMontoTotal(call.getBigDecimal(9));                        
            result.setFechaAntiguedad(call.getDate(10));                        
        } finally {
            call.close();
        }
        if (resultSets.size() > 0) {
            RowSet[] rowSets = new RowSet[resultSets.size()];
            result.setRowSets((RowSet[]) resultSets.toArray(rowSets));
        }
        return result;
    }
}
