/*
 * Source: ArPagarCaller.java - Generated by OBCOM SQL Wizard 5.1.295
 * Author: Felipe Gonzalez Mendoza (Tesoreria General de la Republica)
 *
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
 *
 * All rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
 * used  under  the  terms of its associated license document. You may NOT copy,
 * modify, sublicense, or distribute this source file or portions of  it  unless
 * previously  authorized in writing by OBCOM INGENIERIA S.A. In any event, this
 * notice and above copyright must always be included verbatim with this file.
 */

package cl.teso.reca.pkgcutservicestrx;

import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;
import javax.sql.DataSource;
import javax.sql.RowSet;

/**
 * Implements a caller of procedure "PKG_CUT_SERVICES_TRX.AR_PAGAR".
 * <pre>
 * IN_USER             VARCHAR2(4000)     Input
 * IN_RUT_IRA          NUMBER             Input
 * IN_RUT_IRA_DV       CHAR(2000)         Input
 * IN_CODIGO_BARRA     VARCHAR2(4000)     Input
 * IN_ID_ORIGEN        VARCHAR2(4000)     Input
 * IN_PAQUETE          VARCHAR2(4000)     Input
 * IN_RUTA             VARCHAR2(4000)     Input
 * IN_FOLIO_F01        NUMBER             Input
 * IN_FECHA_ORIGEN     DATE               Input
 * IN_LOTE_CANAL       NUMBER             Input
 * IN_LOTE_TIPO        NUMBER             Input
 * IN_CUT_MOV_ESTADO   NUMBER             Input
 * IN_ES_REVERSA       CHAR(2000)         Input
 * IN_FRM_OPCION       CHAR(2000)         Input
 * IN_FMT_DATA_ERR     VARCHAR2(4000)     Input
 * OUT_ERRLVL          NUMBER             Output
 * OUT_MENSAJES        VARCHAR2(4000)     Output
 * OUT_CONTEST_ID      VARCHAR2(4000)     Output
 * OUT_RECA_MSG        REF CURSOR         Output
 * OUT_FECHA_CONTABLE  DATE               Output
 * </pre>
 */
public class ArPagarCaller extends ProcedureCaller
{
    /**
     * Executes procedure "PKG_CUT_SERVICES_TRX.AR_PAGAR" using a DataSource.
     */
    public static ArPagarResult execute(DataSource dataSource, String inUser, BigDecimal inRutIra, String inRutIraDv, String inCodigoBarra, String inIdOrigen, String inPaquete, String inRuta, BigDecimal inFolioF01, Date inFechaOrigen, BigDecimal inLoteCanal, BigDecimal inLoteTipo, BigDecimal inCutMovEstado, String inEsReversa, String inFrmOpcion, String inFmtDataErr)
        throws SQLException
    {
        Connection conn = dataSource.getConnection();
        try {
            return execute(conn, inUser, inRutIra, inRutIraDv, inCodigoBarra, inIdOrigen, inPaquete, inRuta, inFolioF01, inFechaOrigen, inLoteCanal, inLoteTipo, inCutMovEstado, inEsReversa, inFrmOpcion, inFmtDataErr);
        } finally {
            conn.close();
        }
    }

    /**
     * Executes procedure "PKG_CUT_SERVICES_TRX.AR_PAGAR" using a Connection.
     */
    public static ArPagarResult execute(Connection conn, String inUser, BigDecimal inRutIra, String inRutIraDv, String inCodigoBarra, String inIdOrigen, String inPaquete, String inRuta, BigDecimal inFolioF01, Date inFechaOrigen, BigDecimal inLoteCanal, BigDecimal inLoteTipo, BigDecimal inCutMovEstado, String inEsReversa, String inFrmOpcion, String inFmtDataErr)
        throws SQLException
    {
        ArPagarResult result = new ArPagarResult();
        ArrayList resultSets = new ArrayList();
        if (conn.getMetaData().getURL().startsWith("jdbc:oracle:")) {
            CallableStatement call = conn.prepareCall("{call PKG_CUT_SERVICES_TRX.AR_PAGAR(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)}");
            try {
                call.setString(1, inUser);
                call.setBigDecimal(2, inRutIra);
                call.setString(3, inRutIraDv);
                call.setString(4, inCodigoBarra);
                call.setString(5, inIdOrigen);
                call.setString(6, inPaquete);
                call.setString(7, inRuta);
                call.setBigDecimal(8, inFolioF01);
                call.setTimestamp(9, toTimestamp(inFechaOrigen));
                call.setBigDecimal(10, inLoteCanal);
                call.setBigDecimal(11, inLoteTipo);
                call.setBigDecimal(12, inCutMovEstado);
                call.setString(13, inEsReversa);
                call.setString(14, inFrmOpcion);
                call.setString(15, inFmtDataErr);
                call.registerOutParameter(16, Types.NUMERIC);
                call.registerOutParameter(17, Types.VARCHAR);
                call.registerOutParameter(18, Types.VARCHAR);
                call.registerOutParameter(19, ORACLE_CURSOR);
                call.registerOutParameter(20, Types.TIMESTAMP);
                call.execute();
                result.setOutErrlvl(call.getBigDecimal(16));
                result.setOutMensajes(call.getString(17));
                result.setOutContestId(call.getString(18));
                resultSets.add(toRowSet((ResultSet)call.getObject(19)));
                result.setOutFechaContable(call.getTimestamp(20));
            } finally {
                call.close();
            }
        } else {
            CallableStatement call = conn.prepareCall("{call PKG_CUT_SERVICES_TRX.AR_PAGAR(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)}");
            try {
                call.setString(1, inUser);
                call.setBigDecimal(2, inRutIra);
                call.setString(3, inRutIraDv);
                call.setString(4, inCodigoBarra);
                call.setString(5, inIdOrigen);
                call.setString(6, inPaquete);
                call.setString(7, inRuta);
                call.setBigDecimal(8, inFolioF01);
                call.setTimestamp(9, toTimestamp(inFechaOrigen));
                call.setBigDecimal(10, inLoteCanal);
                call.setBigDecimal(11, inLoteTipo);
                call.setBigDecimal(12, inCutMovEstado);
                call.setString(13, inEsReversa);
                call.setString(14, inFrmOpcion);
                call.setString(15, inFmtDataErr);
                call.registerOutParameter(16, Types.NUMERIC);
                call.registerOutParameter(17, Types.VARCHAR);
                call.registerOutParameter(18, Types.VARCHAR);
                call.registerOutParameter(19, Types.TIMESTAMP);
                int updateCount = 0;
                boolean haveRset = call.execute();
                while (haveRset || updateCount != -1) {
                    if (!haveRset)
                        updateCount = call.getUpdateCount();
                    else
                        resultSets.add(toRowSet(call.getResultSet()));
                    haveRset = call.getMoreResults();
                }
                result.setOutErrlvl(call.getBigDecimal(16));
                result.setOutMensajes(call.getString(17));
                result.setOutContestId(call.getString(18));
                result.setOutFechaContable(call.getTimestamp(19));
            } finally {
                call.close();
            }
        }
        if (resultSets.size() > 0) {
            RowSet[] rowSets = new RowSet[resultSets.size()];
            result.setRowSets((RowSet[]) resultSets.toArray(rowSets));
        }
        return result;
    }
}
