/*
 * Source: GetCtasCutAdnRsCaller.java - Generated by OBCOM SQL Wizard 5.1.295
 * Author: Felipe Gonzalez Mendoza (Tesoreria General de la Republica)
 *
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
 *
 * All rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
 * used  under  the  terms of its associated license document. You may NOT copy,
 * modify, sublicense, or distribute this source file or portions of  it  unless
 * previously  authorized in writing by OBCOM INGENIERIA S.A. In any event, this
 * notice and above copyright must always be included verbatim with this file.
 */

package cl.teso.reca.pkgcutservicestrx;

import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import javax.sql.DataSource;
import javax.sql.RowSet;

/**
 * Implements a caller of procedure "PKG_CUT_SERVICES_TRX.GET_CTAS_CUT_ADN_RS".
 * <pre>
 * IN_CLIENTE_TIPO    NUMBER             Input
 * IN_RUT_ROL         NUMBER             Input
 * IN_FORM_TIPO       NUMBER             Input
 * IN_FORM_FOLIO      NUMBER             Input
 * IN_PERIODO         DATE               Input
 * IN_INCOBRABLE      CHAR(2000)         Input
 * CURSOR_RET         REF CURSOR         Output
 * </pre>
 */
public class GetCtasCutAdnRsCaller extends ProcedureCaller
{
    /**
     * Executes procedure "PKG_CUT_SERVICES_TRX.GET_CTAS_CUT_ADN_RS" using a DataSource.
     */
    public static GetCtasCutAdnRsResult execute(DataSource dataSource, BigDecimal inClienteTipo, BigDecimal inRutRol, BigDecimal inFormTipo, BigDecimal inFormFolio, Date inPeriodo, String inIncobrable)
        throws SQLException
    {
        Connection conn = dataSource.getConnection();
        try {
            return execute(conn, inClienteTipo, inRutRol, inFormTipo, inFormFolio, inPeriodo, inIncobrable);
        } finally {
            conn.close();
        }
    }

    /**
     * Executes procedure "PKG_CUT_SERVICES_TRX.GET_CTAS_CUT_ADN_RS" using a Connection.
     */
    public static GetCtasCutAdnRsResult execute(Connection conn, BigDecimal inClienteTipo, BigDecimal inRutRol, BigDecimal inFormTipo, BigDecimal inFormFolio, Date inPeriodo, String inIncobrable)
        throws SQLException
    {
        GetCtasCutAdnRsResult result = new GetCtasCutAdnRsResult();
        ArrayList resultSets = new ArrayList();
        if (conn.getMetaData().getURL().startsWith("jdbc:oracle:")) {
            CallableStatement call = conn.prepareCall("{call PKG_CUT_SERVICES_TRX.GET_CTAS_CUT_ADN_RS(?,?,?,?,?,?,?)}");
            try {
                call.setBigDecimal(1, inClienteTipo);
                call.setBigDecimal(2, inRutRol);
                call.setBigDecimal(3, inFormTipo);
                call.setBigDecimal(4, inFormFolio);
                call.setTimestamp(5, toTimestamp(inPeriodo));
                call.setString(6, inIncobrable);
                call.registerOutParameter(7, ORACLE_CURSOR);
                call.execute();
                resultSets.add(toRowSet((ResultSet)call.getObject(7)));
            } finally {
                call.close();
            }
        } else {
            CallableStatement call = conn.prepareCall("{call PKG_CUT_SERVICES_TRX.GET_CTAS_CUT_ADN_RS(?,?,?,?,?,?)}");
            try {
                call.setBigDecimal(1, inClienteTipo);
                call.setBigDecimal(2, inRutRol);
                call.setBigDecimal(3, inFormTipo);
                call.setBigDecimal(4, inFormFolio);
                call.setTimestamp(5, toTimestamp(inPeriodo));
                call.setString(6, inIncobrable);
                int updateCount = 0;
                boolean haveRset = call.execute();
                while (haveRset || updateCount != -1) {
                    if (!haveRset)
                        updateCount = call.getUpdateCount();
                    else
                        resultSets.add(toRowSet(call.getResultSet()));
                    haveRset = call.getMoreResults();
                }
            } finally {
                call.close();
            }
        }
        if (resultSets.size() > 0) {
            RowSet[] rowSets = new RowSet[resultSets.size()];
            result.setRowSets((RowSet[]) resultSets.toArray(rowSets));
        }
        return result;
    }
}
