/*
 * Source: GetTrnReqPagoDataCaller.java - Generated by OBCOM SQL Wizard 5.1.295
 * Author: Felipe Gonzalez Mendoza (Tesoreria General de la Republica)
 *
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
 *
 * All rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
 * used  under  the  terms of its associated license document. You may NOT copy,
 * modify, sublicense, or distribute this source file or portions of  it  unless
 * previously  authorized in writing by OBCOM INGENIERIA S.A. In any event, this
 * notice and above copyright must always be included verbatim with this file.
 */

package cl.teso.reca.pkgcutservicestrx;

import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.sql.DataSource;
import javax.sql.RowSet;

/**
 * Implements a caller of procedure "PKG_CUT_SERVICES_TRX.GET_TRN_REQ_PAGO_DATA".
 * <pre>
 * RETURN_VALUE        REF CURSOR         Return
 * IN_TRN_REQ_PAGO_ID  NUMBER             Input
 * </pre>
 */
public class GetTrnReqPagoDataCaller extends ProcedureCaller
{
    /**
     * Executes procedure "PKG_CUT_SERVICES_TRX.GET_TRN_REQ_PAGO_DATA" using a DataSource.
     */
    public static GetTrnReqPagoDataResult execute(DataSource dataSource, BigDecimal inTrnReqPagoId)
        throws SQLException
    {
        Connection conn = dataSource.getConnection();
        try {
            return execute(conn, inTrnReqPagoId);
        } finally {
            conn.close();
        }
    }

    /**
     * Executes procedure "PKG_CUT_SERVICES_TRX.GET_TRN_REQ_PAGO_DATA" using a Connection.
     */
    public static GetTrnReqPagoDataResult execute(Connection conn, BigDecimal inTrnReqPagoId)
        throws SQLException
    {
        GetTrnReqPagoDataResult result = new GetTrnReqPagoDataResult();
        ArrayList resultSets = new ArrayList();
        if (conn.getMetaData().getURL().startsWith("jdbc:oracle:")) {
            CallableStatement call = conn.prepareCall("{?=call PKG_CUT_SERVICES_TRX.GET_TRN_REQ_PAGO_DATA(?)}");
            try {
                call.registerOutParameter(1, ORACLE_CURSOR);
                call.setBigDecimal(2, inTrnReqPagoId);
                call.execute();
                resultSets.add(toRowSet((ResultSet)call.getObject(1)));
            } finally {
                call.close();
            }
        } else {
            CallableStatement call = conn.prepareCall("{call PKG_CUT_SERVICES_TRX.GET_TRN_REQ_PAGO_DATA(?)}");
            try {
                call.setBigDecimal(1, inTrnReqPagoId);
                int updateCount = 0;
                boolean haveRset = call.execute();
                while (haveRset || updateCount != -1) {
                    if (!haveRset)
                        updateCount = call.getUpdateCount();
                    else
                        resultSets.add(toRowSet(call.getResultSet()));
                    haveRset = call.getMoreResults();
                }
            } finally {
                call.close();
            }
        }
        if (resultSets.size() > 0) {
            RowSet[] rowSets = new RowSet[resultSets.size()];
            result.setRowSets((RowSet[]) resultSets.toArray(rowSets));
        }
        return result;
    }
}
