/*
 * Source: PkgCutServicesTrxFormData.java - Generated by OBCOM SQL Wizard 5.1.295
 * Author: Felipe Gonzalez Mendoza (Tesoreria General de la Republica)
 *
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
 *
 * All rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
 * used  under  the  terms of its associated license document. You may NOT copy,
 * modify, sublicense, or distribute this source file or portions of  it  unless
 * previously  authorized in writing by OBCOM INGENIERIA S.A. In any event, this
 * notice and above copyright must always be included verbatim with this file.
 */

package cl.teso.reca.pkgcutservicestrx;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Implements the "PKG_CUT_SERVICES$TRX_FORM_DATA" user-defined object.
 */
public class PkgCutServicesTrxFormData implements Serializable
{
    private static final long serialVersionUID = 1L;

    // Fields of the user-defined object
    private String      usuario;         // VARCHAR2(4000)
    private BigDecimal  rutIra;          // NUMBER
    private String      rutIraDv;        // CHAR(1)
    private BigDecimal  rutContrib;      // NUMBER
    private String      dvContrib;       // CHAR(1)
    private String      signoForm;       // CHAR(1)
    private BigDecimal  formTipo;        // NUMBER
    private String      formVer;         // CHAR(1)
    private BigDecimal  formFolio;           // NUMBER
    private Date        periodo;         // DATE
    private String      items;           // VARCHAR2(4000)
    private String      idOrigen;        // VARCHAR2(4000)
    private String      paquete;         // VARCHAR2(4000)
    private String      ruta;            // VARCHAR2(4000)
    private BigDecimal  folioF01;        // NUMBER
    private Date        fechaOrigen;     // DATE
    private Date        fechaCaja;       // DATE
    private BigDecimal  loteId;          // NUMBER
    private BigDecimal  loteCanal;       // NUMBER
    private BigDecimal  loteTipo;        // NUMBER
    private BigDecimal  cutMovEstado;    // NUMBER
    private String      esReversa;       // CHAR(1)
    private BigDecimal  movIdAnular;     // NUMBER
    private String      frmOpcion;       // CHAR(1)
    private String      fmtDataErr;      // VARCHAR2(4000)
    private String      fmtDataSal;      // VARCHAR2(4000)
    private String      motivo;          // VARCHAR2(4000)
    private String      resolucion;      // VARCHAR2(4000)

    /**
     * Constructor.
     */
    public PkgCutServicesTrxFormData()
    {
    }

    /**
     * Gets the USUARIO value of this PkgCutServicesTrxFormData.
     */
    public String getUsuario()
    {
        return usuario;
    }

    /**
     * Sets the USUARIO value of this PkgCutServicesTrxFormData.
     */
    public void setUsuario(String usuario)
    {
        this.usuario = usuario;
    }

    /**
     * Gets the RUT_IRA value of this PkgCutServicesTrxFormData.
     */
    public BigDecimal getRutIra()
    {
        return rutIra;
    }

    /**
     * Sets the RUT_IRA value of this PkgCutServicesTrxFormData.
     */
    public void setRutIra(BigDecimal rutIra)
    {
        this.rutIra = rutIra;
    }

    /**
     * Gets the RUT_IRA_DV value of this PkgCutServicesTrxFormData.
     */
    public String getRutIraDv()
    {
        return rutIraDv;
    }

    /**
     * Sets the RUT_IRA_DV value of this PkgCutServicesTrxFormData.
     */
    public void setRutIraDv(String rutIraDv)
    {
        this.rutIraDv = rutIraDv;
    }

    /**
     * Gets the RUT_CONTRIB value of this PkgCutServicesTrxFormData.
     */
    public BigDecimal getRutContrib()
    {
        return rutContrib;
    }

    /**
     * Sets the RUT_CONTRIB value of this PkgCutServicesTrxFormData.
     */
    public void setRutContrib(BigDecimal rutContrib)
    {
        this.rutContrib = rutContrib;
    }

    /**
     * Gets the DV_CONTRIB value of this PkgCutServicesTrxFormData.
     */
    public String getDvContrib()
    {
        return dvContrib;
    }

    /**
     * Sets the DV_CONTRIB value of this PkgCutServicesTrxFormData.
     */
    public void setDvContrib(String dvContrib)
    {
        this.dvContrib = dvContrib;
    }

    /**
     * Gets the SIGNO_FORM value of this PkgCutServicesTrxFormData.
     */
    public String getSignoForm()
    {
        return signoForm;
    }

    /**
     * Sets the SIGNO_FORM value of this PkgCutServicesTrxFormData.
     */
    public void setSignoForm(String signoForm)
    {
        this.signoForm = signoForm;
    }

    /**
     * Gets the FORM_TIPO value of this PkgCutServicesTrxFormData.
     */
    public BigDecimal getFormTipo()
    {
        return formTipo;
    }

    /**
     * Sets the FORM_TIPO value of this PkgCutServicesTrxFormData.
     */
    public void setFormTipo(BigDecimal formTipo)
    {
        this.formTipo = formTipo;
    }

    /**
     * Gets the FORM_VER value of this PkgCutServicesTrxFormData.
     */
    public String getFormVer()
    {
        return formVer;
    }

    /**
     * Sets the FORM_VER value of this PkgCutServicesTrxFormData.
     */
    public void setFormVer(String formVer)
    {
        this.formVer = formVer;
    }

    /**
     * Gets the FOLIO value of this PkgCutServicesTrxFormData.
     */
    public BigDecimal getFormFolio()
    {
        return formFolio;
    }

    /**
     * Sets the FOLIO value of this PkgCutServicesTrxFormData.
     */
    public void setFormFolio(BigDecimal formFolio)
    {
        this.formFolio = formFolio;
    }

    /**
     * Gets the PERIODO value of this PkgCutServicesTrxFormData.
     */
    public Date getPeriodo()
    {
        return periodo;
    }

    /**
     * Sets the PERIODO value of this PkgCutServicesTrxFormData.
     */
    public void setPeriodo(Date periodo)
    {
        this.periodo = periodo;
    }

    /**
     * Gets the ITEMS value of this PkgCutServicesTrxFormData.
     */
    public String getItems()
    {
        return items;
    }

    /**
     * Sets the ITEMS value of this PkgCutServicesTrxFormData.
     */
    public void setItems(String items)
    {
        this.items = items;
    }

    /**
     * Gets the ID_ORIGEN value of this PkgCutServicesTrxFormData.
     */
    public String getIdOrigen()
    {
        return idOrigen;
    }

    /**
     * Sets the ID_ORIGEN value of this PkgCutServicesTrxFormData.
     */
    public void setIdOrigen(String idOrigen)
    {
        this.idOrigen = idOrigen;
    }

    /**
     * Gets the PAQUETE value of this PkgCutServicesTrxFormData.
     */
    public String getPaquete()
    {
        return paquete;
    }

    /**
     * Sets the PAQUETE value of this PkgCutServicesTrxFormData.
     */
    public void setPaquete(String paquete)
    {
        this.paquete = paquete;
    }

    /**
     * Gets the RUTA value of this PkgCutServicesTrxFormData.
     */
    public String getRuta()
    {
        return ruta;
    }

    /**
     * Sets the RUTA value of this PkgCutServicesTrxFormData.
     */
    public void setRuta(String ruta)
    {
        this.ruta = ruta;
    }

    /**
     * Gets the FOLIO_F01 value of this PkgCutServicesTrxFormData.
     */
    public BigDecimal getFolioF01()
    {
        return folioF01;
    }

    /**
     * Sets the FOLIO_F01 value of this PkgCutServicesTrxFormData.
     */
    public void setFolioF01(BigDecimal folioF01)
    {
        this.folioF01 = folioF01;
    }

    /**
     * Gets the FECHA_ORIGEN value of this PkgCutServicesTrxFormData.
     */
    public Date getFechaOrigen()
    {
        return fechaOrigen;
    }

    /**
     * Sets the FECHA_ORIGEN value of this PkgCutServicesTrxFormData.
     */
    public void setFechaOrigen(Date fechaOrigen)
    {
        this.fechaOrigen = fechaOrigen;
    }

    /**
     * Gets the FECHA_CAJA value of this PkgCutServicesTrxFormData.
     */
    public Date getFechaCaja()
    {
        return fechaCaja;
    }

    /**
     * Sets the FECHA_CAJA value of this PkgCutServicesTrxFormData.
     */
    public void setFechaCaja(Date fechaCaja)
    {
        this.fechaCaja = fechaCaja;
    }

    /**
     * Gets the LOTE_ID value of this PkgCutServicesTrxFormData.
     */
    public BigDecimal getLoteId()
    {
        return loteId;
    }

    /**
     * Sets the LOTE_ID value of this PkgCutServicesTrxFormData.
     */
    public void setLoteId(BigDecimal loteId)
    {
        this.loteId = loteId;
    }

    /**
     * Gets the LOTE_CANAL value of this PkgCutServicesTrxFormData.
     */
    public BigDecimal getLoteCanal()
    {
        return loteCanal;
    }

    /**
     * Sets the LOTE_CANAL value of this PkgCutServicesTrxFormData.
     */
    public void setLoteCanal(BigDecimal loteCanal)
    {
        this.loteCanal = loteCanal;
    }

    /**
     * Gets the LOTE_TIPO value of this PkgCutServicesTrxFormData.
     */
    public BigDecimal getLoteTipo()
    {
        return loteTipo;
    }

    /**
     * Sets the LOTE_TIPO value of this PkgCutServicesTrxFormData.
     */
    public void setLoteTipo(BigDecimal loteTipo)
    {
        this.loteTipo = loteTipo;
    }

    /**
     * Gets the CUT_MOV_ESTADO value of this PkgCutServicesTrxFormData.
     */
    public BigDecimal getCutMovEstado()
    {
        return cutMovEstado;
    }

    /**
     * Sets the CUT_MOV_ESTADO value of this PkgCutServicesTrxFormData.
     */
    public void setCutMovEstado(BigDecimal cutMovEstado)
    {
        this.cutMovEstado = cutMovEstado;
    }

    /**
     * Gets the ES_REVERSA value of this PkgCutServicesTrxFormData.
     */
    public String getEsReversa()
    {
        return esReversa;
    }

    /**
     * Sets the ES_REVERSA value of this PkgCutServicesTrxFormData.
     */
    public void setEsReversa(String esReversa)
    {
        this.esReversa = esReversa;
    }

    /**
     * Gets the MOV_ID_ANULAR value of this PkgCutServicesTrxFormData.
     */
    public BigDecimal getMovIdAnular()
    {
        return movIdAnular;
    }

    /**
     * Sets the MOV_ID_ANULAR value of this PkgCutServicesTrxFormData.
     */
    public void setMovIdAnular(BigDecimal movIdAnular)
    {
        this.movIdAnular = movIdAnular;
    }

    /**
     * Gets the FRM_OPCION value of this PkgCutServicesTrxFormData.
     */
    public String getFrmOpcion()
    {
        return frmOpcion;
    }

    /**
     * Sets the FRM_OPCION value of this PkgCutServicesTrxFormData.
     */
    public void setFrmOpcion(String frmOpcion)
    {
        this.frmOpcion = frmOpcion;
    }

    /**
     * Gets the FMT_DATA_ERR value of this PkgCutServicesTrxFormData.
     */
    public String getFmtDataErr()
    {
        return fmtDataErr;
    }

    /**
     * Sets the FMT_DATA_ERR value of this PkgCutServicesTrxFormData.
     */
    public void setFmtDataErr(String fmtDataErr)
    {
        this.fmtDataErr = fmtDataErr;
    }

    /**
     * Gets the FMT_DATA_SAL value of this PkgCutServicesTrxFormData.
     */
    public String getFmtDataSal()
    {
        return fmtDataSal;
    }

    /**
     * Sets the FMT_DATA_SAL value of this PkgCutServicesTrxFormData.
     */
    public void setFmtDataSal(String fmtDataSal)
    {
        this.fmtDataSal = fmtDataSal;
    }

    /**
     * Gets the MOTIVO value of this PkgCutServicesTrxFormData.
     */
    public String getMotivo()
    {
        return motivo;
    }

    /**
     * Sets the MOTIVO value of this PkgCutServicesTrxFormData.
     */
    public void setMotivo(String motivo)
    {
        this.motivo = motivo;
    }

    /**
     * Gets the RESOLUCION value of this PkgCutServicesTrxFormData.
     */
    public String getResolucion()
    {
        return resolucion;
    }

    /**
     * Sets the RESOLUCION value of this PkgCutServicesTrxFormData.
     */
    public void setResolucion(String resolucion)
    {
        this.resolucion = resolucion;
    }
}
