/*
 * Source: PkgCutServicesTrxException.java - Generated by OBCOM SQL Wizard 5.1.295
 * Author: Felipe Gonzalez Mendoza (Tesoreria General de la Republica)
 *
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
 *
 * All rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
 * used  under  the  terms of its associated license document. You may NOT copy,
 * modify, sublicense, or distribute this source file or portions of  it  unless
 * previously  authorized in writing by OBCOM INGENIERIA S.A. In any event, this
 * notice and above copyright must always be included verbatim with this file.
 */

package cl.teso.reca.pkgcutservicestrx;

/**
 * Exception thrown when the execution of a procedure fails.
 */
public class PkgCutServicesTrxException extends Exception
{
    private static final long serialVersionUID = 1L;

    /**
     * Create a new PkgCutServicesTrxException.
     */
    public PkgCutServicesTrxException()
    {
        super();
    }

    /**
     * Create a new PkgCutServicesTrxException with supplied message.
     */
    public PkgCutServicesTrxException(String message)
    {
        super(message);
    }

    /**
     * Create a new PkgCutServicesTrxException with supplied cause.
     */
    public PkgCutServicesTrxException(Throwable cause)
    {
        super(cause);
    }

    /**
     * Create a new PkgCutServicesTrxException with supplied message and cause.
     */
    public PkgCutServicesTrxException(String message, Throwable cause)
    {
        super(message, cause);
    }
}
