/*
 * Source: ProcedureCaller.java - Generated by OBCOM SQL Wizard 5.1.295
 * Author: Felipe Gonzalez Mendoza (Tesoreria General de la Republica)
 *
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
 *
 * All rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
 * used  under  the  terms of its associated license document. You may NOT copy,
 * modify, sublicense, or distribute this source file or portions of  it  unless
 * previously  authorized in writing by OBCOM INGENIERIA S.A. In any event, this
 * notice and above copyright must always be included verbatim with this file.
 */

package cl.teso.reca.pkgcutservicestrx;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.Date;
import javax.sql.RowSet;
import javax.sql.rowset.CachedRowSet;
import com.sun.rowset.CachedRowSetImpl;
//import weblogic.jdbc.rowset.RowSetFactory;
//import weblogic.jdbc.rowset.WLCachedRowSet;

/**
 * Implements methods common to all procedure callers.
 */
public abstract class ProcedureCaller
{
    // The same as oracle.jdbc.OracleTypes.CURSOR
    protected static final int ORACLE_CURSOR = -10;

    //--------------------------------------------------------------------------
    //-- ResultSet methods -----------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Builds a RowSet from the supplied ResultSet.
     */
    protected static RowSet toRowSet(ResultSet resultSet)
        throws SQLException
    {
    	//RowSetFactory factory = RowSetFactory.newInstance();
    	//WLCachedRowSet rowSet = factory.newCachedRowSet();
    	CachedRowSet rowSet = new CachedRowSetImpl();
        rowSet.populate(resultSet);
        return rowSet;
    }

    //--------------------------------------------------------------------------
    //-- DATE/TIME conversion methods ------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Converts the supplied Date to a SQL Timestamp instance.
     */
    protected static Timestamp toTimestamp(Date date)
    {
        if (date == null || date instanceof Timestamp)
            return (Timestamp)date;
        return new Timestamp(date.getTime());
    }

    //--------------------------------------------------------------------------
    //-- Utility methods -------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Returns the supplied string truncated to a maximum length.
     */
    private static String truncate(String value, int maxlen)
    {
        if (value != null && value.length() > maxlen)
            value = value.substring(0, maxlen);
        return value;
    }

    //--------------------------------------------------------------------------
    //-- TRN_AVISO_RECIBO_LIST conversion methods ------------------------------
    //--------------------------------------------------------------------------

    /**
     * Converts an SQL Array to an array of TrnAvisoReciboRowtype.
     */
    protected static TrnAvisoReciboRowtype[] toTrnAvisoReciboList(Object datum)
        throws java.sql.SQLException
    {
        // If datum is null then done
        if (datum == null) return null;

        // Check datum and obtain Array interface
        if (!(datum instanceof java.sql.Array))
            throw new IllegalArgumentException("datum is not an Array");
        java.sql.Array array = (java.sql.Array)datum;

        // Create array of items from Array objects 
        Object[] objects = (Object[])array.getArray();
        TrnAvisoReciboRowtype[] items = new TrnAvisoReciboRowtype[objects.length];

        // Convert Struct objects to TrnAvisoReciboRowtype items
        for (int i = 0; i < objects.length; i++)
            items[i] = toTrnAvisoReciboRowtype(objects[i]);

        // Return items
        return items;
    }

    /**
     * Converts an array of TrnAvisoReciboRowtype to an SQL Array.
     */
    protected static Object dbTrnAvisoReciboList(TrnAvisoReciboRowtype[] items, Connection conn)
        throws java.sql.SQLException
    {
        // If items is null then done
        if (items == null) return null;

        // Convert TrnAvisoReciboRowtype items to SQL Structs
        Object[] objects = new Object[items.length];
        for (int i = 0; i < items.length; i++)
            objects[i] = dbTrnAvisoReciboRowtype(items[i], conn);

        // Create an SQL Array from array of objects
        oracle.sql.ArrayDescriptor descriptor =
            oracle.sql.ArrayDescriptor.createDescriptor("TRN_AVISO_RECIBO_LIST", conn);
        return new oracle.sql.ARRAY(descriptor, conn, objects);
    }

    //--------------------------------------------------------------------------
    //-- TBL_CHAR_T conversion methods -----------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Converts an SQL Array to an array of String.
     */
    protected static String[] toTblChar(Object datum)
        throws java.sql.SQLException
    {
        // If datum is null then done
        if (datum == null) return null;

        // Check datum and obtain Array interface
        if (!(datum instanceof java.sql.Array))
            throw new IllegalArgumentException("datum is not an Array");
        java.sql.Array array = (java.sql.Array)datum;

        // Return array of String
        return (String[])array.getArray();
    }

    /**
     * Converts an array of String to an SQL Array.
     */
    protected static Object dbTblChar(String[] items, Connection conn)
        throws java.sql.SQLException
    {
        // If items is null then done
        if (items == null) return null;

        // Create an SQL Array from array of objects
        oracle.sql.ArrayDescriptor descriptor =
            oracle.sql.ArrayDescriptor.createDescriptor("TBL_CHAR_T", conn);
        return new oracle.sql.ARRAY(descriptor, conn, items);
    }

    //--------------------------------------------------------------------------
    //-- TBL_NUM_T conversion methods ------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Converts an SQL Array to an array of BigDecimal.
     */
    protected static BigDecimal[] toTblNum(Object datum)
        throws java.sql.SQLException
    {
        // If datum is null then done
        if (datum == null) return null;

        // Check datum and obtain Array interface
        if (!(datum instanceof java.sql.Array))
            throw new IllegalArgumentException("datum is not an Array");
        java.sql.Array array = (java.sql.Array)datum;

        // Return array of BigDecimal
        return (BigDecimal[])array.getArray();
    }

    /**
     * Converts an array of BigDecimal to an SQL Array.
     */
    protected static Object dbTblNum(BigDecimal[] items, Connection conn)
        throws java.sql.SQLException
    {
        // If items is null then done
        if (items == null) return null;

        // Create an SQL Array from array of objects
        oracle.sql.ArrayDescriptor descriptor =
            oracle.sql.ArrayDescriptor.createDescriptor("TBL_NUM_T", conn);
        return new oracle.sql.ARRAY(descriptor, conn, items);
    }

    //--------------------------------------------------------------------------
    //-- PKG_CUT_SERVICES$TRX_FORM_ARR conversion methods ----------------------
    //--------------------------------------------------------------------------

    /**
     * Converts an SQL Array to an array of PkgCutServicesTrxFormData.
     */
    protected static PkgCutServicesTrxFormData[] toPkgCutServicesTrxFormArr(Object datum)
        throws java.sql.SQLException
    {
        // If datum is null then done
        if (datum == null) return null;

        // Check datum and obtain Array interface
        if (!(datum instanceof java.sql.Array))
            throw new IllegalArgumentException("datum is not an Array");
        java.sql.Array array = (java.sql.Array)datum;

        // Create array of items from Array objects 
        Object[] objects = (Object[])array.getArray();
        PkgCutServicesTrxFormData[] items = new PkgCutServicesTrxFormData[objects.length];

        // Convert Struct objects to PkgCutServicesTrxFormData items
        for (int i = 0; i < objects.length; i++)
            items[i] = toPkgCutServicesTrxFormData(objects[i]);

        // Return items
        return items;
    }

    /**
     * Converts an array of PkgCutServicesTrxFormData to an SQL Array.
     */
    protected static Object dbPkgCutServicesTrxFormArr(PkgCutServicesTrxFormData[] items, Connection conn)
        throws java.sql.SQLException
    {
        // If items is null then done
        if (items == null) return null;

        // Convert PkgCutServicesTrxFormData items to SQL Structs
        Object[] objects = new Object[items.length];
        for (int i = 0; i < items.length; i++)
            objects[i] = dbPkgCutServicesTrxFormData(items[i], conn);

        // Create an SQL Array from array of objects
        oracle.sql.ArrayDescriptor descriptor =
            oracle.sql.ArrayDescriptor.createDescriptor("PKG_CUT_SERVICES$TRX_FORM_ARR", conn);
        return new oracle.sql.ARRAY(descriptor, conn, objects);
    }

    //--------------------------------------------------------------------------
    //-- TRN_AVISO_RECIBO_ROWTYPE conversion methods ---------------------------
    //--------------------------------------------------------------------------

    /**
     * Converts an SQL Struct to an instance of TrnAvisoReciboRowtype.
     */
    protected static TrnAvisoReciboRowtype toTrnAvisoReciboRowtype(Object datum)
        throws java.sql.SQLException
    {
        // If datum is null then done
        if (datum == null) return null;

        // Check datum and obtain Struct interface
        if (!(datum instanceof java.sql.Struct))
            throw new IllegalArgumentException("datum is not a Struct");
        java.sql.Struct struct = (java.sql.Struct)datum;

        // Obtain Struct attributes and check size
        Object[] attributes = struct.getAttributes();
        if (attributes == null || attributes.length != 26)
            throw new IllegalArgumentException("invalid Struct attributes");

        // Create TrnAvisoReciboRowtype from Struct attributes
        TrnAvisoReciboRowtype result = new TrnAvisoReciboRowtype();
        result.setId((BigDecimal)attributes[0]);
        result.setFolio((BigDecimal)attributes[1]);
        result.setFechaCaja((Date)attributes[2]);
        result.setFechaEmision((Date)attributes[3]);
        result.setFechaValidez((Date)attributes[4]);
        result.setSistema((BigDecimal)attributes[5]);
        result.setUsuario((String)attributes[6]);
        result.setClienteTipo((BigDecimal)attributes[7]);
        result.setRutRol((BigDecimal)attributes[8]);
        result.setRutRolDv((String)attributes[9]);
        result.setFormCod((BigDecimal)attributes[10]);
        result.setFormVer((String)attributes[11]);
        result.setFormFolio((BigDecimal)attributes[12]);
        result.setFormFolioDv((String)attributes[13]);
        result.setPeriodo((Date)attributes[14]);
        result.setFechaVcto((Date)attributes[15]);
        result.setItems((String)attributes[16]);
        result.setItemsCut((String)attributes[17]);
        result.setMoneda((BigDecimal)attributes[18]);
        result.setMontoPlazo((BigDecimal)attributes[19]);
        result.setMontoTotal((BigDecimal)attributes[20]);
        result.setReajustes((BigDecimal)attributes[21]);
        result.setIntereses((BigDecimal)attributes[22]);
        result.setMultas((BigDecimal)attributes[23]);
        result.setCondonaciones((BigDecimal)attributes[24]);
        result.setCodigoBarra((String)attributes[25]);
        return result;
    }

    /**
     * Converts an instance of TrnAvisoReciboRowtype to an SQL Struct.
     */
    protected static Object dbTrnAvisoReciboRowtype(TrnAvisoReciboRowtype item, Connection conn)
        throws java.sql.SQLException
    {
        // If item is null then done
        if (item == null) return null;

        // Create array of Struct attributes
        Object[] attributes = new Object[26];
        attributes[0] = item.getId();
        attributes[1] = item.getFolio();
        attributes[2] = toTimestamp(item.getFechaCaja());
        attributes[3] = toTimestamp(item.getFechaEmision());
        attributes[4] = toTimestamp(item.getFechaValidez());
        attributes[5] = item.getSistema();
        attributes[6] = truncate(item.getUsuario(), 15);
        attributes[7] = item.getClienteTipo();
        attributes[8] = item.getRutRol();
        attributes[9] = truncate(item.getRutRolDv(), 1);
        attributes[10] = item.getFormCod();
        attributes[11] = truncate(item.getFormVer(), 1);
        attributes[12] = item.getFormFolio();
        attributes[13] = truncate(item.getFormFolioDv(), 1);
        attributes[14] = toTimestamp(item.getPeriodo());
        attributes[15] = toTimestamp(item.getFechaVcto());
        attributes[16] = truncate(item.getItems(), 4000);
        attributes[17] = truncate(item.getItemsCut(), 4000);
        attributes[18] = item.getMoneda();
        attributes[19] = item.getMontoPlazo();
        attributes[20] = item.getMontoTotal();
        attributes[21] = item.getReajustes();
        attributes[22] = item.getIntereses();
        attributes[23] = item.getMultas();
        attributes[24] = item.getCondonaciones();
        attributes[25] = truncate(item.getCodigoBarra(), 4000);

        // Create an SQL Struct from array of attributes
        oracle.sql.StructDescriptor descriptor =
            oracle.sql.StructDescriptor.createDescriptor("TRN_AVISO_RECIBO_ROWTYPE", conn);
        return new oracle.sql.STRUCT(descriptor, conn, attributes);
    }

    //--------------------------------------------------------------------------
    //-- PKG_CUT_SERVICES$TRX_FORM_DATA conversion methods ---------------------
    //--------------------------------------------------------------------------

    /**
     * Converts an SQL Struct to an instance of PkgCutServicesTrxFormData.
     */
    protected static PkgCutServicesTrxFormData toPkgCutServicesTrxFormData(Object datum)
        throws java.sql.SQLException
    {
        // If datum is null then done
        if (datum == null) return null;

        // Check datum and obtain Struct interface
        if (!(datum instanceof java.sql.Struct))
            throw new IllegalArgumentException("datum is not a Struct");
        java.sql.Struct struct = (java.sql.Struct)datum;

        // Obtain Struct attributes and check size
        Object[] attributes = struct.getAttributes();
        if (attributes == null || attributes.length != 28)
            throw new IllegalArgumentException("invalid Struct attributes");

        // Create PkgCutServicesTrxFormData from Struct attributes
        PkgCutServicesTrxFormData result = new PkgCutServicesTrxFormData();
        result.setUsuario((String)attributes[0]);
        result.setRutIra((BigDecimal)attributes[1]);
        result.setRutIraDv((String)attributes[2]);
        result.setRutContrib((BigDecimal)attributes[3]);
        result.setDvContrib((String)attributes[4]);
        result.setSignoForm((String)attributes[5]);
        result.setFormTipo((BigDecimal)attributes[6]);
        result.setFormVer((String)attributes[7]);
        result.setFormFolio((BigDecimal)attributes[8]);
        result.setPeriodo((Date)attributes[9]);
        result.setItems((String)attributes[10]);
        result.setIdOrigen((String)attributes[11]);
        result.setPaquete((String)attributes[12]);
        result.setRuta((String)attributes[13]);
        result.setFolioF01((BigDecimal)attributes[14]);
        result.setFechaOrigen((Date)attributes[15]);
        result.setFechaCaja((Date)attributes[16]);
        result.setLoteId((BigDecimal)attributes[17]);
        result.setLoteCanal((BigDecimal)attributes[18]);
        result.setLoteTipo((BigDecimal)attributes[19]);
        result.setCutMovEstado((BigDecimal)attributes[20]);
        result.setEsReversa((String)attributes[21]);
        result.setMovIdAnular((BigDecimal)attributes[22]);
        result.setFrmOpcion((String)attributes[23]);
        result.setFmtDataErr((String)attributes[24]);
        result.setFmtDataSal((String)attributes[25]);
        result.setMotivo((String)attributes[26]);
        result.setResolucion((String)attributes[27]);
        return result;
    }

    /**
     * Converts an instance of PkgCutServicesTrxFormData to an SQL Struct.
     */
    protected static Object dbPkgCutServicesTrxFormData(PkgCutServicesTrxFormData item, Connection conn)
        throws java.sql.SQLException
    {
        // If item is null then done
        if (item == null) return null;

        // Create array of Struct attributes
        Object[] attributes = new Object[28];
        attributes[0] = truncate(item.getUsuario(), 4000);
        attributes[1] = item.getRutIra();
        attributes[2] = truncate(item.getRutIraDv(), 1);
        attributes[3] = item.getRutContrib();
        attributes[4] = truncate(item.getDvContrib(), 1);
        attributes[5] = truncate(item.getSignoForm(), 1);
        attributes[6] = item.getFormTipo();
        attributes[7] = truncate(item.getFormVer(), 1);
        attributes[8] = item.getFormFolio();
        attributes[9] = toTimestamp(item.getPeriodo());
        attributes[10] = truncate(item.getItems(), 4000);
        attributes[11] = truncate(item.getIdOrigen(), 4000);
        attributes[12] = truncate(item.getPaquete(), 4000);
        attributes[13] = truncate(item.getRuta(), 4000);
        attributes[14] = item.getFolioF01();
        attributes[15] = toTimestamp(item.getFechaOrigen());
        attributes[16] = toTimestamp(item.getFechaCaja());
        attributes[17] = item.getLoteId();
        attributes[18] = item.getLoteCanal();
        attributes[19] = item.getLoteTipo();
        attributes[20] = item.getCutMovEstado();
        attributes[21] = truncate(item.getEsReversa(), 1);
        attributes[22] = item.getMovIdAnular();
        attributes[23] = truncate(item.getFrmOpcion(), 1);
        attributes[24] = truncate(item.getFmtDataErr(), 4000);
        attributes[25] = truncate(item.getFmtDataSal(), 4000);
        attributes[26] = truncate(item.getMotivo(), 4000);
        attributes[27] = truncate(item.getResolucion(), 4000);

        // Create an SQL Struct from array of attributes
        oracle.sql.StructDescriptor descriptor =
            oracle.sql.StructDescriptor.createDescriptor("PKG_CUT_SERVICES$TRX_FORM_DATA", conn);
        return new oracle.sql.STRUCT(descriptor, conn, attributes);
    }
    
    /**
     * Converts an SQL Struct to an instance of TrnAvisoReciboMRowtype.
     */
    protected static TrnAvisoReciboMRowtype toTrnAvisoReciboMRowtype(Object datum)
        throws java.sql.SQLException
    {
        // If datum is null then done
        if (datum == null) return null;

        // Check datum and obtain Struct interface
        if (!(datum instanceof java.sql.Struct))
            throw new IllegalArgumentException("datum is not a Struct");
        java.sql.Struct struct = (java.sql.Struct)datum;

        // Obtain Struct attributes and check size
        Object[] attributes = struct.getAttributes();
        if (attributes == null || attributes.length != 29)
            throw new IllegalArgumentException("invalid Struct attributes");

        // Create TrnAvisoReciboRowtype from Struct attributes
        TrnAvisoReciboMRowtype result = new TrnAvisoReciboMRowtype();
        result.setId((BigDecimal)attributes[0]);
        result.setFolio((BigDecimal)attributes[1]);
        result.setFechaCaja((Date)attributes[2]);
        result.setFechaEmision((Date)attributes[3]);
        result.setFechaValidez((Date)attributes[4]);
        result.setSistema((BigDecimal)attributes[5]);
        result.setUsuario((String)attributes[6]);
        result.setClienteTipo((BigDecimal)attributes[7]);
        result.setRutRol((BigDecimal)attributes[8]);
        result.setRutRolDv((String)attributes[9]);
        result.setFormCod((BigDecimal)attributes[10]);
        result.setFormVer((String)attributes[11]);
        result.setFormFolio((BigDecimal)attributes[12]);
        result.setFormFolioDv((String)attributes[13]);
        result.setPeriodo((Date)attributes[14]);
        result.setFechaVcto((Date)attributes[15]);
        result.setItems((String)attributes[16]);
        result.setItemsCut((String)attributes[17]);
        result.setMoneda((BigDecimal)attributes[18]);
        result.setMontoPlazo((BigDecimal)attributes[19]);
        result.setMontoTotal((BigDecimal)attributes[20]);
        result.setReajustes((BigDecimal)attributes[21]);
        result.setIntereses((BigDecimal)attributes[22]);
        result.setMultas((BigDecimal)attributes[23]);
        result.setCondonaciones((BigDecimal)attributes[24]);
        result.setCodigoBarra((String)attributes[25]);
        result.setPorcCond((BigDecimal)attributes[26]);
        result.setObligatoria((String)attributes[27]);
        result.setFechaAntiguedad((Date)attributes[28]);
        return result;
}
    
    /**
    * Converts an instance of TrnAvisoReciboRowtype to an SQL Struct.
    */
   protected static Object dbTrnAvisoReciboMRowtype(TrnAvisoReciboMRowtype item, Connection conn)
       throws java.sql.SQLException
   {
       // If item is null then done
       if (item == null) return null;

       // Create array of Struct attributes
       Object[] attributes = new Object[29];
       attributes[0] = item.getId();
       attributes[1] = item.getFolio();
       attributes[2] = toTimestamp(item.getFechaCaja());
       attributes[3] = toTimestamp(item.getFechaEmision());
       attributes[4] = toTimestamp(item.getFechaValidez());
       attributes[5] = item.getSistema();
       attributes[6] = truncate(item.getUsuario(), 15);
       attributes[7] = item.getClienteTipo();
       attributes[8] = item.getRutRol();
       attributes[9] = truncate(item.getRutRolDv(), 1);
       attributes[10] = item.getFormCod();
       attributes[11] = truncate(item.getFormVer(), 1);
       attributes[12] = item.getFormFolio();
       attributes[13] = truncate(item.getFormFolioDv(), 1);
       attributes[14] = toTimestamp(item.getPeriodo());
       attributes[15] = toTimestamp(item.getFechaVcto());
       attributes[16] = truncate(item.getItems(), 4000);
       attributes[17] = truncate(item.getItemsCut(), 4000);
       attributes[18] = item.getMoneda();
       attributes[19] = item.getMontoPlazo();
       attributes[20] = item.getMontoTotal();
       attributes[21] = item.getReajustes();
       attributes[22] = item.getIntereses();
       attributes[23] = item.getMultas();
       attributes[24] = item.getCondonaciones();
       attributes[25] = truncate(item.getCodigoBarra(), 4000);
       attributes[26] = item.getPorcCond();
       attributes[27] = truncate(item.getObligatoria(), 1);
       attributes[28] = toTimestamp(item.getFechaAntiguedad());

       // Create an SQL Struct from array of attributes
       oracle.sql.StructDescriptor descriptor =
           oracle.sql.StructDescriptor.createDescriptor("TRN_AVISO_RECIBOM_ROWTYPE", conn);
       return new oracle.sql.STRUCT(descriptor, conn, attributes);
   }
   
   /**
    * Converts an array of TrnAvisoReciboRowtype to an SQL Array.
    */
   protected static Object dbTrnAvisoReciboMList(TrnAvisoReciboMRowtype[] items, Connection conn)
       throws java.sql.SQLException
   {
       // If items is null then done
       if (items == null) return null;

       // Convert TrnAvisoReciboRowtype items to SQL Structs
       Object[] objects = new Object[items.length];
       for (int i = 0; i < items.length; i++)
           objects[i] = dbTrnAvisoReciboMRowtype(items[i], conn);

       // Create an SQL Array from array of objects
       oracle.sql.ArrayDescriptor descriptor =
           oracle.sql.ArrayDescriptor.createDescriptor("TRN_AVISO_RECIBO_MULTI_LIST", conn);
       return new oracle.sql.ARRAY(descriptor, conn, objects);
   }
   
   /**
    * Converts an SQL Array to an array of TrnAvisoReciboRowtype.
    */
   protected static TrnAvisoReciboMRowtype[] toTrnAvisoReciboMList(Object datum)
       throws java.sql.SQLException
   {
       // If datum is null then done
       if (datum == null) return null;

       // Check datum and obtain Array interface
       if (!(datum instanceof java.sql.Array))
           throw new IllegalArgumentException("datum is not an Array");
       java.sql.Array array = (java.sql.Array)datum;

       // Create array of items from Array objects 
       Object[] objects = (Object[])array.getArray();
       TrnAvisoReciboMRowtype[] items = new TrnAvisoReciboMRowtype[objects.length];

       // Convert Struct objects to TrnAvisoReciboRowtype items
       for (int i = 0; i < objects.length; i++)
           items[i] = toTrnAvisoReciboMRowtype(objects[i]);

       // Return items
       return items;
   }
    
}
