/*
 * Source: AdfValidaCaller.java - Generated by OBCOM SQL Wizard 5.1.295
 * Author: Felipe Gonzalez Mendoza (Tesoreria General de la Republica)
 *
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
 *
 * All rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
 * used  under  the  terms of its associated license document. You may NOT copy,
 * modify, sublicense, or distribute this source file or portions of  it  unless
 * previously  authorized in writing by OBCOM INGENIERIA S.A. In any event, this
 * notice and above copyright must always be included verbatim with this file.
 */

package cl.teso.reca.pkgcutservicestrx;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import javax.sql.DataSource;
import javax.sql.RowSet;

/**
 * Implements a caller of procedure "PKG_CUT_SERVICES_TRX.SIST_RET_PORC_CONDONA".
 * <pre>
 * TOUPLESTGF         VARCHAR2(4000)     Input
 * CONTEXTTGFIN       VARCHAR2(4000)     Input
 * ITEMS_OUT          VARCHAR2(4000)     Output
 * CONTEXTTGFOUT      VARCHAR2(4000)     Output
 * MESSAGESTGF        VARCHAR2(4000)     Output
 * RESULTADO          NUMBER             Output
 * </pre>
 */
public class SistRetPorcCondonaCaller extends ProcedureCaller
{
    /**
     * Executes procedure "PKG_CUT_SERVICES_TRX.SIST_RET_PORC_CONDONA" using a DataSource.
     */
    public static SistRetPorcCondonaResult execute(DataSource dataSource, String sistemaCondonacion)
        throws SQLException
    {
        Connection conn = dataSource.getConnection();
        try {
            return execute(conn, sistemaCondonacion);
        } finally {
            conn.close();
        }
    }

    /**
     * Executes procedure "PKG_CUT_SERVICES_TRX.SIST_RET_PORC_CONDONA" using a Connection.
     */
    public static SistRetPorcCondonaResult execute(Connection conn, String sistemaCondonacion)
        throws SQLException
    {
    	SistRetPorcCondonaResult result = new SistRetPorcCondonaResult();
        ArrayList resultSets = new ArrayList();
        CallableStatement call = conn.prepareCall("{call PKG_CUT_SERVICES_TRX.SIST_RET_PORC_CONDONA(?,?)}");
        try {
            call.setString(1, sistemaCondonacion);            
            call.registerOutParameter(2, Types.VARCHAR);            
            int updateCount = 0;
            boolean haveRset = call.execute();
            while (haveRset || updateCount != -1) {
                if (!haveRset)
                    updateCount = call.getUpdateCount();
                else
                    resultSets.add(toRowSet(call.getResultSet()));
                haveRset = call.getMoreResults();
            }
            result.setRetornaPorc(call.getString(2));
        } finally {
            call.close();
        }
        if (resultSets.size() > 0) {
            RowSet[] rowSets = new RowSet[resultSets.size()];
            result.setRowSets((RowSet[]) resultSets.toArray(rowSets));
        }
        return result;
    }
}
