/*
 * Source: TrxFormFullMasivoCaller.java - Generated by OBCOM SQL Wizard 5.1.295
 * Author: Felipe Gonzalez Mendoza (Tesoreria General de la Republica)
 *
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
 *
 * All rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
 * used  under  the  terms of its associated license document. You may NOT copy,
 * modify, sublicense, or distribute this source file or portions of  it  unless
 * previously  authorized in writing by OBCOM INGENIERIA S.A. In any event, this
 * notice and above copyright must always be included verbatim with this file.
 */

package cl.teso.reca.pkgcutservicestrx;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import javax.sql.DataSource;
import javax.sql.RowSet;

/**
 * Implements a caller of procedure "PKG_CUT_SERVICES_TRX.TRX_FORM_FULL_MASIVO".
 * <pre>
 * IN_LABEL           VARCHAR2(4000)                 Input
 * IN_LISTA_FORM      PKG_CUT_SERVICES$TRX_FORM_ARR  Input
 * OUT_TRN_TRAN_ID    NUMBER                         Output
 * OUT_ERRLVL         NUMBER                         Output
 * OUT_MENSAJES       VARCHAR2(4000)                 Output
 * OUT_RECA_MSG       REF CURSOR                     Output
 * </pre>
 */
public class TrxFormFullMasivoCaller extends ProcedureCaller
{
    /**
     * Executes procedure "PKG_CUT_SERVICES_TRX.TRX_FORM_FULL_MASIVO" using a DataSource.
     */
    public static TrxFormFullMasivoResult execute(DataSource dataSource, String inLabel, PkgCutServicesTrxFormData[] inListaForm)
        throws SQLException
    {
        Connection conn = dataSource.getConnection();
        try {
            return execute(conn, inLabel, inListaForm);
        } finally {
            conn.close();
        }
    }

    /**
     * Executes procedure "PKG_CUT_SERVICES_TRX.TRX_FORM_FULL_MASIVO" using a Connection.
     */
    public static TrxFormFullMasivoResult execute(Connection conn, String inLabel, PkgCutServicesTrxFormData[] inListaForm)
        throws SQLException
    {
        TrxFormFullMasivoResult result = new TrxFormFullMasivoResult();
        ArrayList resultSets = new ArrayList();
        if (conn.getMetaData().getURL().startsWith("jdbc:oracle:")) {
            CallableStatement call = conn.prepareCall("{call PKG_CUT_SERVICES_TRX.TRX_FORM_FULL_MASIVO(?,?,?,?,?,?)}");
            try {
                call.setString(1, inLabel);
                call.setObject(2, dbPkgCutServicesTrxFormArr(inListaForm, conn));
                call.registerOutParameter(3, Types.NUMERIC);
                call.registerOutParameter(4, Types.NUMERIC);
                call.registerOutParameter(5, Types.VARCHAR);
                call.registerOutParameter(6, ORACLE_CURSOR);
                call.execute();
                result.setOutTrnTranId(call.getBigDecimal(3));
                result.setOutErrlvl(call.getBigDecimal(4));
                result.setOutMensajes(call.getString(5));
                resultSets.add(toRowSet((ResultSet)call.getObject(6)));
            } finally {
                call.close();
            }
        } else {
            CallableStatement call = conn.prepareCall("{call PKG_CUT_SERVICES_TRX.TRX_FORM_FULL_MASIVO(?,?,?,?,?)}");
            try {
                call.setString(1, inLabel);
                call.setObject(2, dbPkgCutServicesTrxFormArr(inListaForm, conn));
                call.registerOutParameter(3, Types.NUMERIC);
                call.registerOutParameter(4, Types.NUMERIC);
                call.registerOutParameter(5, Types.VARCHAR);
                int updateCount = 0;
                boolean haveRset = call.execute();
                while (haveRset || updateCount != -1) {
                    if (!haveRset)
                        updateCount = call.getUpdateCount();
                    else
                        resultSets.add(toRowSet(call.getResultSet()));
                    haveRset = call.getMoreResults();
                }
                result.setOutTrnTranId(call.getBigDecimal(3));
                result.setOutErrlvl(call.getBigDecimal(4));
                result.setOutMensajes(call.getString(5));
            } finally {
                call.close();
            }
        }
        if (resultSets.size() > 0) {
            RowSet[] rowSets = new RowSet[resultSets.size()];
            result.setRowSets((RowSet[]) resultSets.toArray(rowSets));
        }
        return result;
    }
}
