/*
 * Source: UpdateTrnSafCaller.java - Generated by OBCOM SQL Wizard 5.1.295
 * Author: Felipe Gonzalez Mendoza (Tesoreria General de la Republica)
 *
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
 *
 * All rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
 * used  under  the  terms of its associated license document. You may NOT copy,
 * modify, sublicense, or distribute this source file or portions of  it  unless
 * previously  authorized in writing by OBCOM INGENIERIA S.A. In any event, this
 * notice and above copyright must always be included verbatim with this file.
 */

package cl.teso.reca.pkgcutservicestrx;

import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import javax.sql.DataSource;
import javax.sql.RowSet;

/**
 * Implements a caller of procedure "PKG_CUT_SERVICES_TRX.UPDATE_TRN_SAF".
 * <pre>
 * IN_FOLIO_ENVIO     NUMBER             Input
 * IN_FECHA_ENVIADO   DATE               Input
 * IN_ENVIADO         VARCHAR2(4000)     Input
 * IN_ESTADO_ENVIO    VARCHAR2(4000)     Input
 * IN_MSG_ENVIO       VARCHAR2(4000)     Input
 * IN_LOG_ENVIO       VARCHAR2(4000)     Input
 * </pre>
 */
public class UpdateTrnSafCaller extends ProcedureCaller
{
    /**
     * Executes procedure "PKG_CUT_SERVICES_TRX.UPDATE_TRN_SAF" using a DataSource.
     */
    public static UpdateTrnSafResult execute(DataSource dataSource, BigDecimal inFolioEnvio, Date inFechaEnviado, String inEnviado, String inEstadoEnvio, String inMsgEnvio, String inLogEnvio)
        throws SQLException
    {
        Connection conn = dataSource.getConnection();
        try {
            return execute(conn, inFolioEnvio, inFechaEnviado, inEnviado, inEstadoEnvio, inMsgEnvio, inLogEnvio);
        } finally {
            conn.close();
        }
    }

    /**
     * Executes procedure "PKG_CUT_SERVICES_TRX.UPDATE_TRN_SAF" using a Connection.
     */
    public static UpdateTrnSafResult execute(Connection conn, BigDecimal inFolioEnvio, Date inFechaEnviado, String inEnviado, String inEstadoEnvio, String inMsgEnvio, String inLogEnvio)
        throws SQLException
    {
        UpdateTrnSafResult result = new UpdateTrnSafResult();
        ArrayList resultSets = new ArrayList();
        CallableStatement call = conn.prepareCall("{call PKG_CUT_SERVICES_TRX.UPDATE_TRN_SAF(?,?,?,?,?,?)}");
        try {
            call.setBigDecimal(1, inFolioEnvio);
            call.setTimestamp(2, toTimestamp(inFechaEnviado));
            call.setString(3, inEnviado);
            call.setString(4, inEstadoEnvio);
            call.setString(5, inMsgEnvio);
            call.setString(6, inLogEnvio);
            int updateCount = 0;
            boolean haveRset = call.execute();
            while (haveRset || updateCount != -1) {
                if (!haveRset)
                    updateCount = call.getUpdateCount();
                else
                    resultSets.add(toRowSet(call.getResultSet()));
                haveRset = call.getMoreResults();
            }
        } finally {
            call.close();
        }
        if (resultSets.size() > 0) {
            RowSet[] rowSets = new RowSet[resultSets.size()];
            result.setRowSets((RowSet[]) resultSets.toArray(rowSets));
        }
        return result;
    }
}
